---
title: "Distribution"
author: "Rubén A. Rodríguez Barrón"
date: "2023-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error = FALSE)
library("tidyverse")
library("amerika")
library("psych")
library("tictoc")
library("plotly")
library("ggrepel")
library("ggfortify")
library("viridis")
library("viridisLite")
library("usmap")
library("usmapdata")
#devtools::install_github(“UrbanInstitute/urbnmapr”)
#library("urbanmapr")
library("data.table")
set.seed(1234)
```

# Import Data
```{r}
# Import taxes
tic()
taxes <- read.csv("IRS.csv")
toc()

# Edit Taxes
taxes <- taxes %>% 
  rename(fips = STATEFIPS, 
         state = STATE)
```



```{r}
# Import spending files
tic()
spend1 <- fread("USASpending_1.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend2 <- fread("USASpending_2.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend3 <- fread("USASpending_3.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend4 <- fread("USASpending_4.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend5 <- fread("USASpending_5.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend6 <- fread("USASpending_6.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

spend7 <- fread("USASpending_7.csv",select = c('parent_award_agency_id','parent_award_agency_name','total_dollars_obligated','awarding_agency_code','awarding_agency_name','awarding_sub_agency_code','awarding_sub_agency_name','awarding_office_code','awarding_office_name','funding_agency_code','funding_agency_name','recipient_country_name','recipient_address_line_1','recipient_address_line_2','recipient_city_name','recipient_county_name','recipient_state_code','recipient_state_name','recipient_zip_4_code','recipient_congressional_district'))

toc()

# create spending
spending <- bind_rows(list(spend1,spend2,spend3,spend4,spend5,spend6,spend7))

# remove spending files
rm(spend1,spend2,spend3,spend4,spend5,spend6,spend7)

# edit spending
spending <- spending %>% 
  rename("state" = "recipient_state_code",
         "zipcode" = "recipient_zip_4_code")

```

```{r}
# Import RUCA
ruca <- read.csv("RUCA.csv")
```


```{r}
glimpse(taxes)
glimpse(spending)
```

# AGI and Spending by State

```{r}
spending %>% 
  count(state)
```


```{r}
taxes %>% 
  group_by(state) %>% 
  summarize(AGI = sum(A00100)) %>% 
  ggplot(aes(state,AGI)) +
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Taxes by State",
       subtitle = "Source: IRS 2020")

spending %>% 
  group_by(state) %>% 
  summarize(spending = sum(total_dollars_obligated)) %>% 
  ggplot(aes(state,spending)) +
  geom_col() +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Spending by State",
       subtitle = "Source: USA Spending 2020")
```


# Charitable Contributions by State

```{r}
tic()

donor <- taxes %>% 
  select(fips,state,N1,A19700) %>% 
  group_by(state) %>% 
  summarize(donations = sum(A19700)/sum(N1))


  plot_usmap(data = donor,
             regions = "states",
             values = "donations",
             color = "black") + 
  scale_fill_continuous(low = "white",
                        high = "blue",
                        name = "Donations") +
  labs(title = "Donations per Capita by State",
       subtitle = "Source: IRS (2020)")

toc()
```

